spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: lb://cliente
          predicates:
            - Path=/cliente/**
        - id: endereco
          uri: lb://endereco
          predicates:
            - Path=/endereco/**
server:
  port: ${PORTA:8080}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka